<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>ru.senioravanti.commons</groupId>
  <artifactId>files</artifactId>
  <version>1.0.0</version>

  <name>files</name>
  <url>https://maven.apache.org</url>

  <packaging>jar</packaging>

  <properties>
    <java.version>25</java.version>

    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    <apache.tika.version>3.3.2</apache.tika.version>
    <junit.version>6.1.1</junit.version>

    <!-- Maven plugins -->
    <maven-compiler-plugin.version>3.14.1</maven-compiler-plugin.version>

    <!-- Custom properties -->
    <main.class>${project.groupId}.${project.artifactId}.App</main.class>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>${junit.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <!-- Tika -->
    <dependency>
      <groupId>org.apache.tika</groupId>
      <artifactId>tika-core</artifactId>
      <version>${apache.tika.version}</version>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${maven-compiler-plugin.version}</version>
        <configuration>
          <source>${java.version}</source>
          <target>${java.version}</target>
          <encoding>UTF-8</encoding>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>